import tkinter as tk
from tkinter import *
from utils import resource_path
from tkinter import ttk, messagebox, filedialog
from PIL import Image, ImageTk
import os
from collections import defaultdict
import mysql.connector
from datetime import datetime, timedelta
import cv2
import numpy as np
import csv
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import matplotlib.dates as mdates
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import requests
import calendar
import threading
from informing import Inform
from openai import OpenAI
import os
from dotenv import load_dotenv
from utils import get_executable_dir

env_path = os.path.join(get_executable_dir(), '.env')
load_dotenv(dotenv_path=env_path)

# Global cache for holidays to avoid repeated API calls across instances
HOLIDAY_CACHE = {}  # year -> set(dates)



ai_client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENAI_API_KEY"),
)


class DetailedAttendanceReport:
    def __init__(self, parent, mydata):
        self.window = Toplevel(parent)
        self.window.title("Advanced Attendance Analytics Dashboard")
        self.window.geometry("1400x800")
        self.window.state('zoomed')
        self.window.minsize(1100, 700) # Ensure content fits 
        self.window.configure(bg='#ecf0f1')
        try:
            self.window.iconbitmap(resource_path('college_images\\bg1.ico'))
        except:
            pass
        
        # Raw Data
        self.mydata = mydata
        
        # --- OPTIMIZATION: Internal Caches ---
        self.attendance_map = {}      # {student_id: {date_str: status}}
        self.working_days_cache = {}  # {(month, year): count}
        self.student_db_cache = {}    # {roll_no: {details}}
        self.photo_cache = []         # To prevent GC of images
        
        # --- OPTIMIZATION: Pre-process data once ---
        self.preprocess_data()
        self.stats = self.calculate_statistics()
        
        # Month data
        self.setup_month_data()
        
        # UI Setup
        self.setup_styles()
        self.create_header()
        self.create_tabs()

    def draw_branding(self, canvas, doc):
        canvas.saveState()

        # Logo
        if os.path.exists(resource_path("assets/logo.png")):
            canvas.drawImage(
                resource_path("assets/logo.png"),
                40, 800,
                width=50,
                height=50,
                preserveAspectRatio=True
            )

        # Footer
        canvas.setFont("Helvetica", 9)
        canvas.drawRightString(
            550, 30,
            f"Page {doc.page} | Generated by Face Recognition System"
        )

        # Watermark
        canvas.setFont("Helvetica-Bold", 60)
        canvas.setFillColorRGB(0.9, 0.9, 0.9)
        canvas.translate(300, 400)
        canvas.rotate(45)
        canvas.drawCentredString(0, 0, "DEV")

        canvas.restoreState()

    def preprocess_data(self):
        """
        OPTIMIZATION: Convert list-based data to dictionary-based lookups.
        Reduces lookup time from O(N) to O(1).
        """
        self.attendance_map = defaultdict(dict)
        for row in self.mydata:
            if len(row) >= 7:
                s_id = row[0]
                date_str = row[5]
                status = row[6].strip().lower()
                self.attendance_map[s_id][date_str] = status

    def setup_month_data(self):
        """Setup last 6 months data"""
        today = datetime.now()
        self.months = []
        
        for i in range(6):
            month_date = today - timedelta(days=30*i)
            month_name = month_date.strftime("%B %Y")
            month_num = month_date.month
            year = month_date.year
            days_in_month = calendar.monthrange(year, month_num)[1]
            
            self.months.append({
                'name': month_name,
                'month': month_num,
                'year': year,
                'days': days_in_month
            })

    def setup_styles(self):
        """Configure professional styling"""
        style = ttk.Style()
        style.theme_use('clam')
        
        # Colors
        self.colors = {
            'primary': '#2c3e50',
            'secondary': '#34495e',
            'accent': '#3498db',
            'success': '#27ae60',
            'warning': '#f39c12',
            'danger': '#e74c3c',
            'bg': '#ecf0f1',
            'card': '#ffffff'
        }
        
        style.configure('TNotebook', background=self.colors['bg'], borderwidth=0)
        style.configure('TNotebook.Tab', 
                       padding=[20, 12], 
                       font=('Segoe UI', 11, 'bold'),
                       background='#bdc3c7',
                       foreground='#2c3e50')
        style.map('TNotebook.Tab', 
                 background=[('selected', self.colors['accent'])],
                 foreground=[('selected', 'white')])
        
        style.configure("Vertical.TScrollbar", gripcount=0,
                background=self.colors['secondary'], darkcolor=self.colors['primary'], 
                lightcolor=self.colors['primary'], troughcolor=self.colors['bg'], 
                bordercolor=self.colors['bg'], arrowcolor='white')

    def create_header(self):
        """Top Header Bar"""
        header = Frame(self.window, bg=self.colors['primary'], height=80)
        header.pack(fill=X, side=TOP)
        header.pack_propagate(False)
        
        Label(header, text="📊", font=('Segoe UI Emoji', 35), 
              bg=self.colors['primary'], fg='white').pack(side=LEFT, padx=20)
        
        titles = Frame(header, bg=self.colors['primary'])
        titles.pack(side=LEFT, pady=10)
        Label(titles, text="ATTENDANCE INTELLIGENCE", font=('Segoe UI', 20, 'bold'), 
              bg=self.colors['primary'], fg='white').pack(anchor=W)
        Label(titles, text="Real-time Student Performance Monitoring", font=('Segoe UI', 10), 
              bg=self.colors['primary'], fg='#bdc3c7').pack(anchor=W)
        
        btn_frame = Frame(header, bg=self.colors['primary'])
        btn_frame.pack(side=RIGHT, padx=20)

        Button(
            btn_frame,
            text="📢 Inform",
            font=('Segoe UI', 10, 'bold'),
            bg=self.colors['accent'],
            fg='white',
            bd=0,
            padx=15,
            pady=5,
            cursor='hand2',
            command=self.open_inform
        ).pack(side=LEFT, padx=5)


        Button(btn_frame, text="📄 Export PDF", font=('Segoe UI', 10, 'bold'), 
               bg=self.colors['warning'], fg='white', bd=0, padx=15, pady=5, cursor='hand2',
               command=self.export_pdf).pack(side=LEFT, padx=5)

        Button(btn_frame, text="✕ Close", font=('Segoe UI', 10), 
               bg=self.colors['danger'], fg='white', bd=0, padx=15, pady=5, cursor='hand2',
               command=self.window.destroy).pack(side=LEFT, padx=5)
    
    def fetch_holidays(self, year, country="IN"):
        """Fetch holidays with caching and timeout safety"""
        if year in HOLIDAY_CACHE:
            return HOLIDAY_CACHE[year]

        url = f"https://date.nager.at/api/v3/PublicHolidays/{year}/{country}"
        try:
            # Short timeout to prevent UI freezing
            response = requests.get(url, timeout=5)
            if response.status_code == 200:
                data = response.json()
                holidays = {
                    datetime.strptime(h["date"], "%Y-%m-%d").date()
                    for h in data
                }
                HOLIDAY_CACHE[year] = holidays
                return holidays
        except Exception as e:
            print(f"Warning: Could not fetch holidays for {year}: {e}")
            
        # Fallback to empty set if fetch fails
        HOLIDAY_CACHE[year] = set()
        return set()

    def calculate_working_days(self, month, year):
        """
        OPTIMIZATION: Memoized working days calculation.
        """
        cache_key = (month, year)
        if cache_key in self.working_days_cache:
            return self.working_days_cache[cache_key]

        holidays = self.fetch_holidays(year)
        total_days = calendar.monthrange(year, month)[1]

        working_days = 0
        for day in range(1, total_days + 1):
            try:
                current_date = datetime(year, month, day).date()
                if current_date.weekday() == 6:  # Sunday
                    continue
                if current_date in holidays:     # Holiday
                    continue
                working_days += 1
            except ValueError:
                continue

        self.working_days_cache[cache_key] = working_days
        return working_days

    def create_tabs(self):
        """Main Tab Controller"""
        container = Frame(self.window, bg=self.colors['bg'])
        container.pack(fill=BOTH, expand=True, padx=20, pady=20)
        
        self.notebook = ttk.Notebook(container)
        self.notebook.pack(fill=BOTH, expand=True)
        
        # 1. Overview Tab
        self.tab_overview = Frame(self.notebook, bg='white')
        self.notebook.add(self.tab_overview, text=' 📈 Executive Overview ')
        # Use 'after' to let UI render before heavy computation if needed
        self.create_overview_tab()
        
        # 2. Analytics Tab
        self.tab_analytics = Frame(self.notebook, bg='white')
        self.notebook.add(self.tab_analytics, text=' 📊 Statistical Analytics ')
        self.create_analytics_tab()
        
        # 3. Monthly Analysis Tab
        self.tab_monthly = Frame(self.notebook, bg='white')
        self.notebook.add(self.tab_monthly, text=' 📅 Monthly Analysis ')
        self.create_monthly_tab()

        # 4. Student Details Tab
        self.tab_details = Frame(self.notebook, bg='white')
        self.notebook.add(self.tab_details, text=' 👤 Individual Report ')
        self.create_details_tab()

    def calculate_statistics(self):
        """Process raw data into usable statistics"""
        # We can now use the pre-processed attendance_map for faster counting
        # But for initial setup, iterating once is fine.
        
        # Re-using the logic but ensuring we handle duplicates correctly
        attendance_summary = defaultdict(lambda: {'present': 0, 'absent': 0, 'total': 0, 'dates': []})
        
        # Fast lookup meta info
        meta_info = {}
        
        for row in self.mydata:
            if len(row) >= 7:
                student_id = row[0]
                
                # Store meta info only once per student
                if student_id not in meta_info:
                    meta_info[student_id] = {
                        'name': row[1],
                        'roll': row[2],
                        'dept': row[3],
                        'time': row[4]
                    }
                
                date_str = row[5]
                status = row[6].strip().lower()
                
                attendance_summary[student_id]['total'] += 1
                attendance_summary[student_id]['dates'].append(date_str)
                
                if status == 'present':
                    attendance_summary[student_id]['present'] += 1
                else:
                    attendance_summary[student_id]['absent'] += 1
        
        stats_list = []
        for s_id, data in attendance_summary.items():
            meta = meta_info.get(s_id)
            if meta:
                percentage = (data['present'] / data['total'] * 100) if data['total'] > 0 else 0
                stats_list.append({
                    'id': s_id,
                    'name': meta['name'],
                    'roll': meta['roll'],
                    'dept': meta['dept'],
                    'time': meta['time'],
                    'present': data['present'],
                    'absent': data['absent'],
                    'total': data['total'],
                    'percentage': percentage,
                    'dates': data['dates'] # Keeps list of dates for specific iterating
                })
        
        return sorted(stats_list, key=lambda x: x['percentage'], reverse=True)

    def get_monthly_attendance(self, student, month_data):
        """
        OPTIMIZATION: Calculate attendance for a specific month using O(1) lookup map.
        """
        month = month_data['month']
        year = month_data['year']
        
        present_days = 0
        total_recorded_days = 0
        
        # We only need to check dates associated with this student
        # Optimize: Filter dates by string parsing is slow, but assuming format DD/MM/YYYY
        # checking the suffix is faster than strptime if date format is strictly consistent.
        # Fallback to strptime for safety.
        
        target_suffix = f"/{month:02d}/{year}" # e.g. /05/2024
        
        # Get the map for this student
        student_att_map = self.attendance_map.get(student['id'], {})
        
        # Iterate only dates this student has records for
        for date_str in student['dates']:
            # Fast string check first
            if date_str.endswith(target_suffix) or f"/{month}/" in date_str:
                try:
                    # Verify exact match
                    d_obj = datetime.strptime(date_str, "%d/%m/%Y")
                    if d_obj.month == month and d_obj.year == year:
                        total_recorded_days += 1
                        # O(1) Lookup instead of iterating mydata
                        status = student_att_map.get(date_str, "").lower()
                        if status == 'present':
                            present_days += 1
                except ValueError:
                    continue

        working_days = self.calculate_working_days(month, year)
        return present_days, total_recorded_days, working_days

    def get_student_image(self, student_id, size=(100, 100)):
        """Load student image with error handling"""
        img_path = None
        
        # Prioritize color image
        color_path = resource_path(f"data/user.{student_id}.5.jpg")
        
        if os.path.exists(color_path):
            img_path = color_path
        else:
            # Check other samples
            for i in range(1, 6):
                temp_path = resource_path(f"data/user.{student_id}.{i}.jpg")
                if os.path.exists(temp_path):
                    img_path = temp_path
                    break
        
        if img_path and os.path.exists(img_path):
            try:
                # Optimize: Use Pillow directly if cv2 is not strictly needed for processing
                # But sticking to cv2 as per original logic, just ensuring safety
                cv_img = cv2.imread(img_path)
                if cv_img is not None:
                    cv_img = cv2.resize(cv_img, size)
                    rgb_img = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
                    pil_img = Image.fromarray(rgb_img)
                    return ImageTk.PhotoImage(pil_img)
            except Exception as e:
                # Silent fail for image loading to not disrupt UX
                pass
        
        # Fallback placeholder
        placeholder = Image.new('RGB', size, color='#bdc3c7')
        return ImageTk.PhotoImage(placeholder)

    def create_scrollable_canvas(self, parent):
        canvas = Canvas(parent, bg='white', highlightthickness=0)
        scrollbar = ttk.Scrollbar(parent, orient="vertical", command=canvas.yview)
        scrollable_frame = Frame(canvas, bg='white')
        
        scrollable_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all"))
        )
        
        canvas.create_window((0, 0), window=scrollable_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)
        
        canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")
        
        def _on_mousewheel(event):
            canvas.yview_scroll(int(-1*(event.delta/120)), "units")
        
        canvas.bind_all("<MouseWheel>", _on_mousewheel)
        
        return scrollable_frame

    def export_pdf(self):
        try:
            filename = filedialog.asksaveasfilename(
                initialdir=os.getcwd(),
                title="Save PDF Report",
                filetypes=(("PDF File", "*.pdf"),),
                defaultextension=".pdf",
                parent=self.window
            )
            if not filename:
                return

            # ==========================
            # BRANDING
            # ==========================
            
            # ==========================
            # 6 MONTH METRICS (SOURCE OF TRUTH)
            # ==========================
            overview_stats = []
            total_working_days_6m = sum(
                self.calculate_working_days(m['month'], m['year'])
                for m in self.months
            )

            for student in self.stats:
                total_present = 0
                for m in self.months:
                    present, _, _ = self.get_monthly_attendance(student, m)
                    total_present += present

                pct_6m = (
                    (total_present / total_working_days_6m) * 100
                    if total_working_days_6m else 0
                )

                overview_stats.append({
                    **student,
                    "percentage_6m": pct_6m
                })

            # 🔑 RANK BASED ON EXECUTIVE OVERVIEW
            overview_stats.sort(key=lambda x: x["percentage_6m"], reverse=True)

            total_students = len(overview_stats)
            avg_attendance = (
                sum(s["percentage_6m"] for s in overview_stats) / total_students
                if total_students else 0
            )
            critical_count = sum(1 for s in overview_stats if s["percentage_6m"] < 75)

            # ==========================
            # CHARTS
            # ==========================
            chart_files = []

            # --- CHART 1: CATEGORY DISTRIBUTION ---
            dist = self.attendance_category_distribution()

            fig1, ax1 = plt.subplots(figsize=(7, 4))
            labels = list(dist.keys())
            values = list(dist.values())

            bars = ax1.bar(labels, values)

            # 🔢 VALUE LABELS ABOVE BARS
            for bar in bars:
                height = bar.get_height()
                if height == 0:
                    continue
                ax1.text(
                    bar.get_x() + bar.get_width() / 2,
                    height + 0.008,                 # slightly above bar
                    f"{int(height)}",
                    ha='center',
                    va='bottom',
                    fontsize=10,
                    fontweight='bold'
                )

            ax1.set_title("Attendance Category Distribution")
            ax1.set_ylabel("Students")
            ax1.yaxis.set_major_locator(plt.MaxNLocator(integer=True))
            ax1.tick_params(axis='y', labelsize=10)
            ax1.tick_params(axis='x', labelsize=10)
           

            ax1.set_xticks(range(len(labels)))
            ax1.set_xticklabels(labels, rotation=20, ha="right")

            chart1 = resource_path("chart_category.png")
            plt.tight_layout()
            fig1.savefig(chart1, dpi=300, bbox_inches="tight")
            plt.close(fig1)
            chart_files.append(chart1)

            # --- CHART 2: DEPARTMENT PIE ---
            dept_data = defaultdict(int)
            for s in overview_stats:
                dept_data[s['dept']] += 1

            fig2, ax2 = plt.subplots(figsize=(6, 4))
            ax2.pie(
                dept_data.values(),
                labels=dept_data.keys(),
                autopct="%1.1f%%",
                startangle=90
            )
            ax2.set_title("Department-wise Distribution")

            chart2 = resource_path("chart_department.png")
            plt.tight_layout()
            fig2.savefig(chart2, dpi=300, bbox_inches="tight")
            plt.close(fig2)
            chart_files.append(chart2)

            # --- CHART 3: TOP STUDENTS (EXECUTIVE RANK) ---
            top_students = overview_stats[:10]

            fig3, ax3 = plt.subplots(figsize=(6, 4))
            bars = ax3.barh(
            [s["name"][:12] for s in reversed(top_students)],
            [s["percentage_6m"] for s in reversed(top_students)]
        )

            #  VALUE LABELS ON BARS
            for bar in bars:
                width = bar.get_width()
                if width == 0:
                    continue
                ax3.text(
                    width + 0.0075,                    # slightly right of bar
                    bar.get_y() + bar.get_height() / 2,
                    f"{width:.1f}%",
                    va='center',
                    fontsize=9,
                    fontweight='bold'
                )

            ax3.set_xlabel("Attendance Percentage (%)")
            ax3.xaxis.set_major_locator(plt.MultipleLocator(10))
            ax3.tick_params(axis='x', labelsize=10)
            ax3.tick_params(axis='y', labelsize=10)

            ax3.set_xlim(0, 100)
            ax3.set_title("Top Students – Last 6 Months")

            chart3 = resource_path("chart_monthly.png")
            plt.tight_layout()
            fig3.savefig(chart3, dpi=300, bbox_inches="tight")
            plt.close(fig3)
            chart_files.append(chart3)

            # ==========================
            # AI SUMMARY (≤50 WORDS)
            # ==========================
            stats_text = f"""
    Total Students: {total_students}\n
    Average Attendance: {avg_attendance:.2f}%\n
    Students below 75% attendance: {critical_count}\n
    """

            try:
                completion = ai_client.chat.completions.create(
                    extra_headers={"X-Title": "Attendance Intelligence"},
                    model="openai/gpt-oss-120b:free",
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "You are an academic analytics assistant. "
                                "Write a professional executive attendance summary "
                                "for college administrators. "
                                "STRICT LIMIT: Maximum 50 words. "
                                "Use only the provided metrics. "
                                "Do not use bullet points."
                            )
                        },
                        {"role": "user", "content": stats_text}
                    ]
                )
                ai_summary = completion.choices[0].message.content.strip()
            except Exception as e:
                ai_summary = "Executive summary unavailable."

            # ==========================
            # PDF BUILD
            # ==========================
            doc = SimpleDocTemplate(filename, pagesize=A4)
            styles = getSampleStyleSheet()
            elements = []

            title_style = ParagraphStyle(
                "title",
                parent=styles["Heading1"],
                alignment=TA_CENTER,
                fontSize=22
            )

            heading = ParagraphStyle(
                "heading",
                parent=styles["Heading2"],
                textColor=colors.HexColor("#3498db")
            )

            # TITLE
            elements.append(Paragraph("ATTENDANCE INTELLIGENCE REPORT", title_style))
            elements.append(Spacer(1, 20))

            # EXECUTIVE OVERVIEW TABLE
            elements.append(Paragraph("Executive Overview", heading))
            overview_table = Table([
                ["Metric", "Value"],
                ["Total Students", total_students],
                ["Average Attendance (6 Months)", f"{avg_attendance:.2f}%"],
                ["Critical Attendance (<75%)", critical_count]
            ], colWidths=[3 * inch, 2 * inch])

            overview_table.setStyle(TableStyle([
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold")
            ]))

            elements.append(overview_table)
            elements.append(PageBreak())

            # STUDENT RANK TABLE (EXECUTIVE ORDER)
            elements.append(Paragraph("Student Attendance Details", heading))
            table_data = [["Rank", "Name", "Roll", "Dept", "Attendance % (6M)"]]

            for i, s in enumerate(overview_stats[:30], 1):
                table_data.append([
                    i,
                    s["name"],
                    s["roll"],
                    s["dept"],
                    f"{s['percentage_6m']:.1f}%"
                ])

            student_table = Table(table_data, repeatRows=1)
            student_table.setStyle(TableStyle([
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white)
            ]))

            elements.append(student_table)
            elements.append(PageBreak())

            # CHARTS
            elements.append(Paragraph("Statistical Charts", heading))
            for chart in chart_files:
                elements.append(RLImage(chart, width=6 * inch, height=4 * inch))
                elements.append(Spacer(1, 20))

            elements.append(PageBreak())

            # AI SUMMARY
            elements.append(Paragraph("AI Generated Executive Summary", heading))
            elements.append(Paragraph(ai_summary, styles["Normal"]))

            doc.build(
                elements,
                onFirstPage=self.draw_branding,
                onLaterPages=self.draw_branding
            )
            for chart in chart_files:
                try:
                    if os.path.exists(chart):
                        os.remove(chart)
                except Exception as e:
                    print(f"Could not delete {chart}: {e}")

            messagebox.showinfo("Success", "PDF exported successfully!", parent=self.window)

        except Exception as e:
            messagebox.showerror("Error", f"PDF export failed:\n{e}", parent=self.window)

    def create_overview_tab(self):
        container = self.create_scrollable_canvas(self.tab_overview)

        # ============================
        # 6 MONTH GLOBAL CALCULATIONS
        # ============================
        # Pre-calculate working days efficiently
        total_working_days_6m = 0
        for m in self.months:
             total_working_days_6m += self.calculate_working_days(m['month'], m['year'])

        overview_stats = []
        
        # Optimize: Iterate students and calculate locally without repeated redundant calls
        for student in self.stats:
            total_present = 0

            for m in self.months:
                # Use the optimized O(1) monthly getter
                present, _, _ = self.get_monthly_attendance(student, m)
                total_present += present

            percentage_6m = (
                (total_present / total_working_days_6m) * 100
                if total_working_days_6m > 0 else 0
            )

            overview_stats.append({
                **student,
                "present_6m": total_present,
                "percentage_6m": percentage_6m
            })

        # Sort by SAME percentage used in Individual Report
        overview_stats.sort(key=lambda x: x["percentage_6m"], reverse=True)

        # ============================
        # SUMMARY CARDS (6 MONTH BASED)
        # ============================
        summary_frame = Frame(container, bg='white')
        summary_frame.pack(fill=X, padx=40, pady=30)

        total_students = len(overview_stats)
        avg_attendance = (
            sum(s["percentage_6m"] for s in overview_stats) / total_students
            if total_students else 0
        )

        perfect_count = sum(1 for s in overview_stats if s["percentage_6m"] >= 95)
        critical_count = sum(1 for s in overview_stats if s["percentage_6m"] < 75)

        cards = [
            ("TOTAL STUDENTS", str(total_students), self.colors['accent'], "👥"),
            ("AVG ATTENDANCE (6M)", f"{avg_attendance:.1f}%", self.colors['success'], "📊"),
            ("PERFECT (≥95%)", str(perfect_count), self.colors['success'], "⭐"),
            ("CRITICAL (<75%)", str(critical_count), self.colors['danger'], "⚠️")
        ]

        for i, (title, value, color, icon) in enumerate(cards):
            card = Frame(
                summary_frame,
                bg='white',
                highlightbackground=color,
                highlightthickness=2,
                padx=20,
                pady=20
            )
            card.grid(row=0, column=i, padx=10, sticky='ew')
            summary_frame.grid_columnconfigure(i, weight=1)

            Label(card, text=icon, font=('Segoe UI Emoji', 28), bg='white').pack(anchor=W)
            Label(card, text=value, font=('Segoe UI', 30, 'bold'),
                fg=color, bg='white').pack(anchor=W)
            Label(card, text=title, font=('Segoe UI', 10, 'bold'),
                fg='#7f8c8d', bg='white').pack(anchor=W)

        # ============================
        # TOP PERFORMERS LIST (6 MONTH)
        # ============================
        list_frame = Frame(container, bg='white')
        list_frame.pack(fill=BOTH, expand=True, padx=40, pady=20)

        Label(
            list_frame,
            text="🏆 Top Performers (Last 6 Months)",
            font=('Segoe UI', 16, 'bold'),
            bg='white',
            fg=self.colors['primary']
        ).pack(anchor=W, pady=(0, 15))

        headers = [
            "Rank", "Photo", "Name", "Roll No",
            "Department", "Attendance % (6M)", "Status"
        ]

        header_frame = Frame(list_frame, bg=self.colors['secondary'])
        header_frame.pack(fill=X)

        for i, h in enumerate(headers):
            Label(
                header_frame,
                text=h,
                bg=self.colors['secondary'],
                fg='white',
                font=('Segoe UI', 10, 'bold'),
                pady=10
            ).grid(row=0, column=i, sticky='ew')
            header_frame.grid_columnconfigure(i, weight=1)

        # Show Top 10
        for idx, student in enumerate(overview_stats[:10], start=1):
            row_color = '#f9f9f9' if idx % 2 == 0 else 'white'
            row = Frame(list_frame, bg=row_color, pady=6)
            row.pack(fill=X)

            Label(row, text=f"#{idx}", bg=row_color,
                font=('Segoe UI', 11, 'bold')).grid(row=0, column=0, sticky='ew')

            img = self.get_student_image(student['id'], size=(50, 50))
            self.photo_cache.append(img)
            Label(row, image=img, bg=row_color).grid(row=0, column=1)

            Label(row, text=student['name'], bg=row_color).grid(row=0, column=2, sticky='ew')
            Label(row, text=student['roll'], bg=row_color).grid(row=0, column=3, sticky='ew')
            Label(row, text=student['dept'], bg=row_color).grid(row=0, column=4, sticky='ew')

            pct = student["percentage_6m"]
            pct_color = self.colors['success'] if pct >= 75 else self.colors['danger']

            Label(
                row,
                text=f"{pct:.2f}%",
                bg=row_color,
                fg=pct_color,
                font=('Segoe UI', 11, 'bold')
            ).grid(row=0, column=5, sticky='ew')

            status = (
                "Excellent" if pct >= 90 else
                "Good" if pct >= 75 else
                "Low"
            )

            Label(row, text=status, bg=row_color).grid(row=0, column=6, sticky='ew')

            for i in range(7):
                row.grid_columnconfigure(i, weight=1)

    def calculate_6_month_percentage(self, student):
        total_working_days = 0
        total_present = 0
        
        for m in self.months:
            total_working_days += self.calculate_working_days(m['month'], m['year'])
            present, _, _ = self.get_monthly_attendance(student, m)
            total_present += present

        if total_working_days == 0:
            return 0

        return (total_present / total_working_days) * 100

    def attendance_category_distribution(self):
        distribution = {
            "Excellent (≥90%)": 0,
            "Good (75–90%)": 0,
            "Average (50–75%)": 0,
            "Critical (<50%)": 0
        }

        for student in self.stats:
            # Use cached or efficient calculation
            percentage = self.calculate_6_month_percentage(student)

            if percentage >= 90:
                distribution["Excellent (≥90%)"] += 1
            elif percentage >= 75:
                distribution["Good (75–90%)"] += 1
            elif percentage >= 50:
                distribution["Average (50–75%)"] += 1
            else:
                distribution["Critical (<50%)"] += 1

        return distribution

    def create_analytics_tab(self):
        container = self.create_scrollable_canvas(self.tab_analytics)

        # Chart Frame
        chart_frame = Frame(container, bg='white', relief=RIDGE, bd=1)
        chart_frame.pack(fill=BOTH, expand=True, padx=40, pady=30)

        Label(
            chart_frame,
            text="📊 Attendance Distribution Analysis (Last 6 Months)",
            font=('Segoe UI', 16, 'bold'),
            bg='white',
            fg=self.colors['primary']
        ).pack(anchor=W, padx=20, pady=10)

        # Create matplotlib figure
        # Reduced width to 11 to fit smaller screens without scrolling
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 5)) 
        fig.patch.set_facecolor('white')

        # ============================
        # BAR CHART – CATEGORY WISE
        # ============================
        dist = self.attendance_category_distribution()

        labels = list(dist.keys())
        values = list(dist.values())

        colors_chart = [
            self.colors['success'],   # Excellent
            self.colors['accent'],    # Good
            self.colors['warning'],   # Average
            self.colors['danger']     # Critical
        ]

        bars = ax1.bar(
            labels,
            values,
            color=colors_chart,
            edgecolor='black',
            linewidth=1.5
        )

        ax1.set_title(
            "Attendance Category Distribution",
            fontweight='bold',
            pad=15
        )
        ax1.set_ylabel("Number of Students", fontweight='bold')
        ax1.grid(axis='y', linestyle='--', alpha=0.3)

        # Value labels
        for bar in bars:
            height = bar.get_height()
            ax1.text(
                bar.get_x() + bar.get_width() / 2,
                height,
                str(int(height)),
                ha='center',
                va='bottom',
                fontweight='bold'
            )

        # ============================
        # PIE CHART – DEPARTMENT WISE
        # ============================
        dept_data = defaultdict(int)
        for s in self.stats:
            dept_data[s['dept']] += 1

        dept_names = list(dept_data.keys())
        dept_counts = list(dept_data.values())

        colors_pie = plt.cm.Set3(range(len(dept_names)))

        if dept_counts: # Check to avoid error if empty
            wedges, texts, autotexts = ax2.pie(
                dept_counts,
                labels=dept_names,
                autopct='%1.1f%%',
                colors=colors_pie,
                startangle=90
            )

            for autotext in autotexts:
                autotext.set_color('white')
                autotext.set_fontweight('bold')
        else:
             ax2.text(0.5, 0.5, "No Data", ha='center')

        ax2.set_title(
            "Department-wise Student Distribution",
            fontweight='bold',
            pad=15
        )

        plt.tight_layout()

        # Embed matplotlib in Tkinter
        canvas = FigureCanvasTkAgg(fig, master=chart_frame)
        canvas.draw()
        canvas.get_tk_widget().pack(fill=BOTH, expand=True, padx=20, pady=20)

    def create_monthly_tab(self):
        """Monthly Analysis Tab with Chart"""
        container = self.create_scrollable_canvas(self.tab_monthly)
        
        # Month Selector
        selector_frame = Frame(container, bg='white')
        selector_frame.pack(fill=X, padx=40, pady=20)
        
        Label(selector_frame, text="Select Month:", font=('Segoe UI', 14, 'bold'), 
              bg='white').pack(side=LEFT, padx=10)
        
        self.selected_month = StringVar()
        month_combo = ttk.Combobox(selector_frame, textvariable=self.selected_month,
                                  values=[m['name'] for m in self.months],
                                  font=('Segoe UI', 12), width=20, state='readonly')
        month_combo.pack(side=LEFT, padx=10)
        month_combo.current(0)
        
        Button(selector_frame, text="📊 Generate Analysis", 
               font=('Segoe UI', 11, 'bold'),
               bg=self.colors['accent'], fg='white', bd=0, padx=20, pady=8, cursor='hand2',
               command=self.generate_monthly_analysis).pack(side=LEFT, padx=10)
        
        # Results Frame
        self.monthly_results = Frame(container, bg='white')
        self.monthly_results.pack(fill=BOTH, expand=True, padx=40, pady=20)
        btn_frame = Frame(container, bg='white')
        btn_frame.pack(fill=X, padx=40, pady=(10, 30))
        self.print_btn = Button(
            btn_frame,
            text="🖨️ Print Monthly Report",
            font=('Segoe UI', 11, 'bold'),
            bg=self.colors['success'],
            fg='white',
            bd=0,
            padx=20,
            pady=8,
            cursor='hand2',
            state=DISABLED,          # 🔒 disabled by default
            command=self.print_monthly_report
        )
        self.print_btn.pack(side=RIGHT)

    def print_monthly_report(self):
        if self.print_btn['state'] == DISABLED:
            return
        selected = self.selected_month.get()
        month_data = next((m for m in self.months if m['name'] == selected), None)
        if not month_data:
            return

        file = filedialog.asksaveasfilename(
            title="Save Monthly Attendance Report",
            defaultextension=".pdf",
            filetypes=[("PDF File", "*.pdf")],
            parent=self.window
        )
        if not file:
            return

        # =========================
        # MONTHLY STATS
        # =========================
        monthly_stats = []
        for student in self.stats:
            present, attended, total_days = self.get_monthly_attendance(student, month_data)
            if attended > 0:
                pct = (present / total_days * 100) if total_days else 0
                monthly_stats.append({
                    "name": student["name"],
                    "roll": student["roll"],
                    "dept": student["dept"],
                    "present": present,
                    "total": total_days,
                    "percentage": pct
                })

        monthly_stats.sort(key=lambda x: x["percentage"], reverse=True)

        avg_att = sum(s["percentage"] for s in monthly_stats) / len(monthly_stats)
        low_count = sum(1 for s in monthly_stats if s["percentage"] < 75)

        # =========================
        # MONTHLY CHART
        # =========================
        chart_file = resource_path("monthly_chart.png")
        top = monthly_stats[:10]

        fig, ax = plt.subplots(figsize=(7, 4))
        names = [s["name"][:12] for s in top]
        pcts = [s["percentage"] for s in top]

        bars = ax.barh(names, pcts)
        ax.set_xlim(0, 100)
        ax.set_title(f"Top Students – {month_data['name']}")
        ax.set_xlabel("Attendance %")

        for bar in bars:
            if bar.get_width() > 0:
                ax.text(
                    bar.get_width() + 1,
                    bar.get_y() + bar.get_height() / 2,
                    f"{bar.get_width():.1f}%",
                    va="center",
                    fontweight="bold"
                )

        plt.tight_layout()
        fig.savefig(chart_file, dpi=300)
        plt.close(fig)

        # =========================
        # AI INSIGHT
        # =========================
        ai_text = f"""
    Month: {month_data['name']}\n
    Average Attendance: {avg_att:.2f}%\n
    Students below 75%: {low_count}\n
    Total Students: {len(monthly_stats)}\n
    """

        try:
            completion = ai_client.chat.completions.create(
                model="tngtech/deepseek-r1t2-chimera:free",
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "Write a professional monthly attendance insight "
                            "for college administrators. Maximum 40 words. "
                            "No bullet points."
                        )
                    },
                    {"role": "user", "content": ai_text}
                ]
            )
            ai_summary = completion.choices[0].message.content.strip()
        except:
            ai_summary = "AI insight unavailable."

        # =========================
        # PDF BUILD
        # =========================
        doc = SimpleDocTemplate(file, pagesize=A4)
        styles = getSampleStyleSheet()
        elements = []

        elements.append(Paragraph(
            f"MONTHLY ATTENDANCE REPORT – {month_data['name']}",
            styles["Title"]
        ))
        elements.append(Spacer(1, 20))

        # Summary table
        summary = Table([
            ["Metric", "Value"],
            ["Students", len(monthly_stats)],
            ["Average Attendance", f"{avg_att:.2f}%"],
            ["Below 75%", low_count]
        ])

        summary.setStyle(TableStyle([
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("BACKGROUND", (0,0), (-1,0), colors.lightblue),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold")
        ]))

        elements.append(summary)
        elements.append(Spacer(1, 20))

        elements.append(RLImage(chart_file, width=6*inch, height=4*inch))
        elements.append(Spacer(1, 20))

        elements.append(Paragraph("AI Monthly Insight", styles["Heading2"]))
        elements.append(Paragraph(ai_summary, styles["Normal"]))
        elements.append(PageBreak())

        # Detail table
        table_data = [["Rank", "Name", "Roll", "Dept", "Attendance %"]]
        for i, s in enumerate(monthly_stats[:25], 1):
            table_data.append([
                i, s["name"], s["roll"], s["dept"], f"{s['percentage']:.1f}%"
            ])

        table = Table(table_data, repeatRows=1)
        table.setStyle(TableStyle([
            ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
            ("BACKGROUND", (0,0), (-1,0), colors.darkblue),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white)
        ]))

        elements.append(table)

        doc.build(
            elements,
            onFirstPage=self.draw_branding,
            onLaterPages=self.draw_branding
        )

        if os.path.exists(chart_file):
            os.remove(chart_file)

        messagebox.showinfo("Success", "Monthly report printed successfully!",parent=self.window)

    def generate_monthly_analysis(self):
        """Generate monthly attendance analysis"""
        for widget in self.monthly_results.winfo_children():
            widget.destroy()
        
        selected = self.selected_month.get()
        month_data = next((m for m in self.months if m['name'] == selected), None)
        
        if not month_data:
            return
        
        # Calculate monthly stats
        monthly_stats = []
        for student in self.stats:
            present, attended, total_days = self.get_monthly_attendance(student, month_data)
            
            if attended > 0:  # Only include students with attendance in this month
                percentage = (present / total_days * 100) if total_days > 0 else 0
                monthly_stats.append({
                    'student': student,
                    'present': present,
                    'attended': attended,
                    'total_days': total_days,
                    'percentage': percentage
                })
        
            if not monthly_stats:
                Label(
                    self.monthly_results,
                    text="No attendance data found for this month",
                    font=('Segoe UI', 14),
                    bg='white',
                    fg=self.colors['danger']
                ).pack(pady=50)

                # 🔒 Disable print button
                self.print_btn.config(
                    state=DISABLED,
                    bg='#bdc3c7',
                    cursor='arrow'
                )
                return
            self.print_btn.config(
            state=NORMAL,
            bg=self.colors['success'],
            cursor='hand2'
        )


        
        # Sort by percentage
        monthly_stats.sort(key=lambda x: x['percentage'], reverse=True)
        
        # Summary Cards
        summary_frame = Frame(self.monthly_results, bg='white')
        summary_frame.pack(fill=X, pady=20)
        
        avg_attendance = sum(s['percentage'] for s in monthly_stats) / len(monthly_stats)
        total_present = sum(s['present'] for s in monthly_stats)
        total_attended = sum(s['attended'] for s in monthly_stats)
        working_days = self.calculate_working_days(month_data['month'], month_data['year'])
        cards = [
            ("WORKING DAYS", str(working_days), self.colors['primary']),
            ("STUDENTS TRACKED", str(len(monthly_stats)), self.colors['accent']),
            ("AVERAGE ATTENDANCE", f"{avg_attendance:.1f}%",
            self.colors['success'] if avg_attendance > 75 else self.colors['warning']),
            ("TOTAL PRESENT", f"{total_present}/{working_days}", self.colors['success'])
        ]
        
        for idx, (title, val, color) in enumerate(cards):
            card = Frame(summary_frame, bg=color, padx=20, pady=15)
            card.grid(row=0, column=idx, sticky='ew', padx=10)
            summary_frame.grid_columnconfigure(idx, weight=1)
            
            Label(card, text=val, font=('Segoe UI', 28, 'bold'), 
                 fg='white', bg=color).pack()
            Label(card, text=title, font=('Segoe UI', 9, 'bold'), 
                 fg='white', bg=color).pack()
        
        # Chart Frame
        chart_frame = Frame(self.monthly_results, bg='white', relief=RIDGE, bd=1)
        chart_frame.pack(fill=BOTH, expand=True, pady=20)
        
        # Create matplotlib chart
        fig, ax = plt.subplots(figsize=(10, 6))
        fig.patch.set_facecolor('white')
        
        # Prepare data for chart (top 15 students)
        top_students = monthly_stats[:15]
        names = [s['student']['name'][:15] for s in top_students]
        percentages = [s['percentage'] for s in top_students]
        colors_bars = [self.colors['success'] if p >= 75 else self.colors['danger'] 
                      for p in percentages]
        
        if names:
            bars = ax.barh(names, percentages, color=colors_bars, edgecolor='black')
            ax.set_xlabel('Attendance Percentage (%)', fontweight='bold')
            ax.set_title(f'Top 15 Students - {month_data["name"]}', fontweight='bold', pad=20)
            ax.set_xlim(0, 100)
            ax.grid(axis='x', alpha=0.3, linestyle='--')
            
            # Add value labels
            for i, (bar, pct) in enumerate(zip(bars, percentages)):
                ax.text(pct + 2, bar.get_y() + bar.get_height()/2, 
                       f'{pct:.1f}%', va='center', fontweight='bold')
        else:
            ax.text(0.5, 0.5, "No Data for Chart", ha='center')
        
        plt.tight_layout()
        
        canvas = FigureCanvasTkAgg(fig, master=chart_frame)
        canvas.draw()
        canvas.get_tk_widget().pack(fill=BOTH, expand=True, padx=20, pady=20)
        
        # Detailed Table
        table_frame = Frame(self.monthly_results, bg='white')
        table_frame.pack(fill=BOTH, expand=True, pady=20)
        
        Label(table_frame, text=f"Detailed Attendance - {month_data['name']}", 
              font=('Segoe UI', 14, 'bold'), 
              bg='white', fg=self.colors['primary']).pack(anchor=W, pady=10)
        
        # Headers
        headers = [
                "Rank",
                "Name",
                "Roll No",
                "Days Present",
                "Present / Working Days",
                "Percentage",
                "Status"
            ]
        h_frame = Frame(table_frame, bg=self.colors['secondary'])
        h_frame.pack(fill=X)
        
        for i, h in enumerate(headers):
            Label(h_frame, text=h, bg=self.colors['secondary'], fg='white', 
                  font=('Segoe UI', 9, 'bold'), pady=8).grid(row=0, column=i, sticky='ew')
            h_frame.grid_columnconfigure(i, weight=1)
        
        # Data rows
        for idx, stat in enumerate(monthly_stats[:20], 1):
            row_color = '#f9f9f9' if idx % 2 == 0 else 'white'
            row = Frame(table_frame, bg=row_color, pady=5)
            row.pack(fill=X)
            
            student = stat['student']
            
            Label(row, text=f"#{idx}", bg=row_color, 
                 font=('Segoe UI', 10, 'bold')).grid(row=0, column=0, sticky='ew')
            Label(row, text=student['name'][:20], bg=row_color).grid(row=0, column=1, sticky='ew')
            Label(row, text=student['roll'], bg=row_color).grid(row=0, column=2, sticky='ew')
            Label(row, text=str(stat['present']), bg=row_color, 
                 font=('Segoe UI', 10, 'bold')).grid(row=0, column=3, sticky='ew')
            Label(row,text=f"{stat['present']} / {stat['total_days']}",bg=row_color
                ).grid(row=0, column=4, sticky='ew')

            
            pct_color = self.colors['success'] if stat['percentage'] >= 75 else self.colors['danger']
            Label(row, text=f"{stat['percentage']:.1f}%", bg=row_color, 
                 fg=pct_color, font=('Segoe UI', 10, 'bold')).grid(row=0, column=5, sticky='ew')
            
            status = "Excellent" if stat['percentage'] >= 90 else \
                    "Good" if stat['percentage'] >= 75 else "Low"
            Label(row, text=status, bg=row_color).grid(row=0, column=6, sticky='ew')
            
            for i in range(7): 
                row.grid_columnconfigure(i, weight=1)
            if monthly_stats:
                self.print_btn.config(state=NORMAL)
            else:
                self.print_btn.config(state=DISABLED)

    def create_details_tab(self):
        search_frame = Frame(self.tab_details, bg=self.colors['bg'], height=80)
        search_frame.pack(fill=X)
        search_frame.pack_propagate(False)
        
        inner = Frame(search_frame, bg=self.colors['bg'])
        inner.pack(expand=True)
        
        Label(inner, text="Find Student:", font=('Segoe UI', 12), 
              bg=self.colors['bg']).pack(side=LEFT, padx=10)
        
        values = [f"{s['roll']} - {s['name']}" for s in self.stats]
        self.detail_var = StringVar()
        cb = ttk.Combobox(inner, textvariable=self.detail_var, values=values, 
                         width=40, font=('Segoe UI', 11))
        cb.pack(side=LEFT, padx=10)
        
        Button(inner, text="Generate Report", command=self.generate_individual_report,
               bg=self.colors['accent'], fg='white', font=('Segoe UI', 10, 'bold'), 
               bd=0, padx=20, pady=5, cursor='hand2').pack(side=LEFT)

        self.detail_content = Frame(self.tab_details, bg='white')
        self.detail_content.pack(fill=BOTH, expand=True)
        btn_frame = Frame(self.tab_details, bg='white')
        btn_frame.pack(fill=X, padx=40, pady=(10, 30))

        self.print_individual_btn = Button(
            btn_frame,
            text="🖨️ Print Individual Report",
            font=('Segoe UI', 11, 'bold'),
            bg=self.colors['success'],
            fg='white',
            bd=0,
            padx=20,
            pady=8,
            cursor='hand2',
            state=DISABLED,
            command=self.print_individual_report
        )
        self.print_individual_btn.pack(side=RIGHT)

    def generate_individual_report(self):
        self.print_individual_btn.config(
        state=DISABLED,
        bg='#bdc3c7',
        cursor='arrow'
        )

        for w in self.detail_content.winfo_children(): 
            w.destroy()
        
        selection = self.detail_var.get()
        if not selection: 
            return
        
        roll = selection.split(" - ")[0]
        student = next((s for s in self.stats if s['roll'] == roll), None)
        
        if not student: 
            return
        
        container = self.create_scrollable_canvas(self.detail_content)
        
        main_frame = Frame(container, bg='white')
        main_frame.pack(fill=BOTH, expand=True, padx=40, pady=30)
        
        # LEFT PANEL
        left = Frame(main_frame, bg='white', width=350)
        left.pack(side=LEFT, fill=Y, padx=(0, 30))
        
        img = self.get_student_image(student['id'], size=(250, 250))
        if img:
            self.print_individual_btn.config(
                state=NORMAL,
                bg=self.colors['success'],
                cursor='hand2'
            )
        self.photo_cache.append(img)
        photo_frame = Frame(left, bg='white', highlightbackground='#bdc3c7', 
                        highlightthickness=1)
        photo_frame.pack(pady=20)
        Label(photo_frame, image=img, bg='white').pack(padx=5, pady=5)
        
        Label(left, text=student['name'], font=('Segoe UI', 18, 'bold'), 
            bg='white', wraplength=300).pack(pady=10)
        
        # Optimized: Fetch DB details with caching
        db_info = self.fetch_db_details(student['roll'])
        
        info_box = Frame(left, bg='#f9f9f9', padx=15, pady=15)
        info_box.pack(fill=X)
        
        infos = [
            ("Student ID", student['id']),
            ("Roll No", student['roll']),
            ("Department", student['dept']),
            ("Gender", db_info.get('gender', 'N/A')),
            ("Email", db_info.get('email', 'N/A')),
            ("Phone", db_info.get('phone', 'N/A'))
        ]
        
        for k, v in infos:
            row = Frame(info_box, bg='#f9f9f9')
            row.pack(fill=X, pady=5)
            Label(row, text=k, font=('Segoe UI', 10, 'bold'), 
                bg='#f9f9f9', fg='#7f8c8d').pack(side=LEFT)
            Label(row, text=v, font=('Segoe UI', 10), bg='#f9f9f9').pack(side=RIGHT)

        # RIGHT PANEL
        right = Frame(main_frame, bg='white')
        right.pack(side=RIGHT, fill=BOTH, expand=True)
        
        # Last 6 Months Stats Cards in one row
        six_months_frame = Frame(right, bg='white')
        six_months_frame.pack(fill=X, pady=30)
        
        # Calculate total working days, total present, total absent, and average attendance for the last 6 months
        working_days_6_months = 0
        total_present_6_months = 0
        total_absent_6_months = 0
        
        for m in self.months:
            wd = self.calculate_working_days(m['month'], m['year'])
            working_days_6_months += wd
            present, attended, total_days = self.get_monthly_attendance(student, m)
            total_present_6_months += present
            total_absent_6_months += (total_days - present)
        
        avg_pct = (total_present_6_months / working_days_6_months * 100) if working_days_6_months > 0 else 0
        
        six_months_stats = [
            ("Total Working Days", str(working_days_6_months), self.colors['primary']),
            ("Total Present", str(total_present_6_months), self.colors['success']),
            ("Total Absent", str(total_absent_6_months), self.colors['danger']),
            ("Average Attendance %", f"{avg_pct:.2f}%", self.colors['accent'])
        ]
        
        for i, (lbl, val, col) in enumerate(six_months_stats):
            card = Frame(six_months_frame, bg=col, padx=20, pady=15, width=200, height=200)
            card.grid(row=0, column=i, padx=10, sticky='nsew')
            six_months_frame.grid_columnconfigure(i, weight=1)
            
            Label(card, text=val, font=('Segoe UI', 24, 'bold'), fg='white', bg=col).pack(expand=True)
            Label(card, text=lbl, font=('Segoe UI', 9, 'bold'), fg='white', bg=col).pack(expand=True)

        # Performance Visualization
        Label(right, text="Performance Visualization", 
            font=('Segoe UI', 14, 'bold'), bg='white').pack(anchor=W, pady=(20, 10))
        
        pb_canvas = Canvas(right, height=40, bg='#ecf0f1', highlightthickness=0)
        pb_canvas.pack(fill=X)
        
        average_attendance_percentage = avg_pct
        fill_width = (average_attendance_percentage / 100) * 800
        col = self.colors['success'] if average_attendance_percentage >= 75 else self.colors['danger']
        
        pb_canvas.create_rectangle(0, 0, fill_width, 40, fill=col, outline='')
        pb_canvas.create_text(40, 20, text=f"{average_attendance_percentage:.2f}%", 
                            fill='white' if average_attendance_percentage > 5 else 'black', 
                            font=('Segoe UI', 12, 'bold'))

    def print_individual_report(self):
    # 🔒 Safety check
        if self.print_individual_btn['state'] == DISABLED:
            return

        # Save dialog
        file = filedialog.asksaveasfilename(
            title="Save Individual Attendance Report",
            defaultextension=".pdf",
            filetypes=[("PDF File", "*.pdf")],
            parent=self.window
        )
        if not file:
            return

        # Selected student
        selection = self.detail_var.get()
        if not selection:
            return

        roll = selection.split(" - ")[0]
        student = next((s for s in self.stats if s['roll'] == roll), None)
        if not student:
            return

        # =========================
        # STUDENT IMAGE (MANDATORY)
        # =========================
        img_path = f"temp_student_{student['id']}.png"
        try:
            pil_img = ImageTk.getimage(self.photo_cache[-1])
            pil_img.save(img_path)
        except:
            messagebox.showerror("Error", "Student image not available.")
            return

        # =========================
        # ATTENDANCE DATA (6 MONTHS)
        # =========================
        months = []
        percentages = []

        for m in reversed(self.months):
            present, _, total_days = self.get_monthly_attendance(student, m)
            pct = (present / total_days * 100) if total_days > 0 else 0
            months.append(m["name"].split()[0])
            percentages.append(pct)

        overall_pct = self.calculate_6_month_percentage(student)

        # =========================
        # GENERATE CHART
        # =========================
        chart_path = f"chart_individual_{student['id']}.png"

        fig, ax = plt.subplots(figsize=(7, 4))
        bars = ax.bar(months, percentages)

        ax.set_ylim(0, 100)
        ax.set_ylabel("Attendance %")
        ax.set_title("Attendance Trend – Last 6 Months")

        # Auto-hide 0 labels
        for bar, pct in zip(bars, percentages):
            if pct > 0:
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    pct + 1,
                    f"{pct:.1f}%",
                    ha="center",
                    fontweight="bold"
                )

        plt.tight_layout()
        fig.savefig(chart_path, dpi=300)
        plt.close(fig)

        # =========================
        # AI INSIGHT
        # =========================
        ai_prompt = f"""
    Student Name: {student['name']}
    Department: {student['dept']}
    6 Month Attendance: {overall_pct:.2f}%
    """

        try:
            completion = ai_client.chat.completions.create(
                model="tngtech/deepseek-r1t2-chimera:free",
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "Write a professional individual attendance insight "
                            "for college administrators. Maximum 40 words. "
                            "No bullet points."
                        )
                    },
                    {"role": "user", "content": ai_prompt}
                ]
            )
            ai_summary = completion.choices[0].message.content.strip()
        except:
            ai_summary = "AI insight unavailable."

        # =========================
        # PDF BUILD
        # =========================
        doc = SimpleDocTemplate(file, pagesize=A4)
        styles = getSampleStyleSheet()
        elements = []

        # Title
        elements.append(Paragraph("INDIVIDUAL ATTENDANCE REPORT", styles["Title"]))
        elements.append(Spacer(1, 20))

        # Student image
        elements.append(RLImage(img_path, width=2*inch, height=2*inch))
        elements.append(Spacer(1, 15))

        # Student info table
        info_table = Table([
            ["Name", student["name"]],
            ["Roll No", student["roll"]],
            ["Department", student["dept"]],
            ["Attendance (6 Months)", f"{overall_pct:.2f}%"]
        ], colWidths=[2.5*inch, 3.5*inch])

        info_table.setStyle(TableStyle([
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("BACKGROUND", (0,0), (0,-1), colors.lightgrey),
            ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold")
        ]))

        elements.append(info_table)
        elements.append(PageBreak())

        # Chart
        elements.append(Paragraph("Attendance Trend", styles["Heading2"]))
        elements.append(Spacer(1, 10))
        elements.append(RLImage(chart_path, width=6*inch, height=4*inch))
        elements.append(Spacer(1, 20))

        # AI Insight
        elements.append(Paragraph("AI Attendance Insight", styles["Heading2"]))
        elements.append(Paragraph(ai_summary, styles["Normal"]))

        # Build PDF with SAME branding
        doc.build(
            elements,
            onFirstPage=self.draw_branding,
            onLaterPages=self.draw_branding
        )

        # =========================
        # CLEANUP
        # =========================
        for f in [img_path, chart_path]:
            if os.path.exists(f):
                os.remove(f)

        messagebox.showinfo("Success", "Individual report printed successfully!",parent=self.window)

    def open_inform(self):
        inform_window = Toplevel(self.window)
        Inform(inform_window)

    def fetch_db_details(self, roll):
        """
        OPTIMIZATION: Caches database results to avoid reconnection overhead.
        """
        if roll in self.student_db_cache:
            return self.student_db_cache[roll]

        try:
            # Using a context manager for cleaner handling
            conn = mysql.connector.connect(host='localhost', port=3307, 
                                          username='root', password='1582', 
                                          database='face_recognizer')
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM student WHERE Roll=%s", (roll,))
            row = cursor.fetchone()
            conn.close()
            
            if row:
                data = {'gender': row[8], 'email': row[10], 'phone': row[11]}
                self.student_db_cache[roll] = data
                return data
        except Exception as e:
            # Silent fail or log
            print(f"DB Error: {e}")
        
        return {}